# Pipeline selection meta-configuration
version: 1
name: pipeline-selector
description: "Automatic pipeline selection based on change characteristics"

# Pipeline selection rules (evaluated in order)
selection_rules:
  - name: "lightweight"
    pipeline: "lightweight.yaml"
    conditions:
      any:
        - file_count_max: 3
        - line_changes_max: 50
        - scope_matches: ["hotfix", "typo", "minor", "docs-only"]
        - files_only_match: ["*.md", "*.txt", "*.json"]
    description: "Small, low-risk changes"

  - name: "default"
    pipeline: "default.yaml"
    conditions:
      any:
        - file_count_max: 10
        - line_changes_max: 300
        - scope_matches: ["fix", "chore", "refactor"]
        - no_architecture_impact: true
    description: "Standard development workflow"

  - name: "optimized"
    pipeline: "optimized.yaml"
    conditions:
      any:
        - file_count_max: 25
        - multiple_tech_stacks: true
        - scope_matches: ["feature", "enhancement"]
        - has_frontend_and_backend: true
    description: "Context-aware multi-stack changes"

  - name: "extended"
    pipeline: "extended.yaml"
    conditions:
      any:
        - file_count_exceeds: 25
        - scope_matches: ["architecture", "major", "milestone"]
        - has_migrations: true
        - affects_multiple_domains: true
    description: "Comprehensive review for complex changes"

# Default fallback
default_pipeline: "default.yaml"

# Agent availability mapping
agent_mapping:
  "code-author": "01_code-author.md"
  "code-reviewer": "02_code-reviewer.md"
  "architect": "03_architect.md"
  "laravel-expert": "04_laravel-expert.md"
  "filament-expert": "05_filament-expert.md"
  "nova-expert": "06_nova-expert.md"
  "react-expert": "07_react-expert.md"
  "database-expert": "08_database-expert.md"
  "docs-reviewer": "09_docs-reviewer.md"
  "tailwind-expert": "10_tailwind-expert.md"
  "livewire-expert": "11_livewire-expert.md"
  "ux-expert": "12_ux-expert.md"
  "pm": "13_pm.md"
  "coordinator": "14_coordinator.md"
  "github-expert": "15_github-expert.md"

# Performance monitoring
monitoring:
  track_execution_time: true
  track_agent_utilization: true
  track_pipeline_success_rate: true
  generate_reports: true

# Quality metrics
quality_thresholds:
  minimum_score: 6.0
  warning_score: 7.0
  excellent_score: 9.0

notes:
  - "Pipeline selection is automatic based on change characteristics"
  - "All 15 agents are properly mapped and available"
  - "Performance is optimized through conditional execution"
  - "Quality thresholds ensure consistent output"